# Generated by Django 6.0.2 on 2026-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
