# Generated by Django 6.0.2 on 2026-02-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_upload_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
